// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opfryiuywxrwlbguthgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZnJ5aXV5d3hyd2xiZ3V0aGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjExODUsImV4cCI6MjA2OTI5NzE4NX0.5wdM1Y05fRM1XbqpHhNEkIFvpy5qc_HN7CeESoMGgWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});